require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { connectDB, getPool, closeDB } = require('../src/config/database');

async function migrate() {
  try {
    await connectDB();
    const pool = getPool();

    await pool.query(`
      CREATE TABLE IF NOT EXISTS GrammarCategories (
        Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Name varchar(100) NOT NULL,
        NameVI varchar(100),
        Icon varchar(10) DEFAULT 'book',
        OrderIndex integer DEFAULT 0
      )
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS GrammarTopics (
        Id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        CategoryId integer REFERENCES GrammarCategories(Id),
        Title varchar(200) NOT NULL,
        TitleVI varchar(200),
        Content text,
        OrderIndex integer DEFAULT 0
      )
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS GrammarQuiz (
        Id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        TopicId uuid REFERENCES GrammarTopics(Id),
        Question text NOT NULL,
        OptionA varchar(255),
        OptionB varchar(255),
        OptionC varchar(255),
        OptionD varchar(255),
        CorrectAnswer varchar(1),
        Explanation text
      )
    `);

    console.log('Grammar migration completed.');
  } catch (err) {
    console.error('Migration failed:', err);
    process.exitCode = 1;
  } finally {
    await closeDB();
  }
}

migrate();
